[[protocols]]
name = "samsung"
protocol = "nec"
variant = "nec-32"
[protocols.scancodes]
0x9b44a101 = "KEY_NUMERIC_1"
0x9b44a202 = "KEY_NUMERIC_2"
0x9b44a303 = "KEY_NUMERIC_3"
0x9b44a404 = "KEY_NUMERIC_4"
0x9b44a505 = "KEY_NUMERIC_5"
0x9b44a606 = "KEY_NUMERIC_6"
0x9b44a707 = "KEY_NUMERIC_7"
0x9b44a808 = "KEY_NUMERIC_8"
0x9b44a909 = "KEY_NUMERIC_9"
0x9b443100 = "KEY_NUMERIC_0"
0x9b440a11 = "KEY_RIGHT"
0x9b441b10 = "KEY_LEFT"
0x9b440e0b = "KEY_UP"
0x9b440e54 = "KEY_DOWN"
0x9b44460d = "KEY_OK"
