[[protocols]]
name = "samsung"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0x70704 = "KEY_NUMERIC_1"
0x70705 = "KEY_NUMERIC_2"
0x70706 = "KEY_NUMERIC_3"
0x70708 = "KEY_NUMERIC_4"
0x70709 = "KEY_NUMERIC_5"
0x7070a = "KEY_NUMERIC_6"
0x7070c = "KEY_NUMERIC_7"
0x7070d = "KEY_NUMERIC_8"
0x7070e = "KEY_NUMERIC_9"
0x70711 = "KEY_NUMERIC_0"
0x02bd0a = "KEY_MUTE"
0x02bd0b = "KEY_NEW"
0x02bd0e = "KEY_VOLUMEDOWN"
0x02bd0f = "KEY_PLAYPAUSE"
0x70762 = "KEY_RIGHT"
0x70765 = "KEY_LEFT"
0x70760 = "KEY_UP"
0x70761 = "KEY_DOWN"
0x70768 = "KEY_OK"
0x02bd16 = "KEY_STOP"
0x02bd17 = "KEY_CAMERA"
0x02bd18 = "KEY_CHANNELUP"
0x02bd19 = "KEY_RECORD"
0x02bd1a = "KEY_CHANNELDOWN"
0x02bd1c = "KEY_ESC"
0x02bd1f = "KEY_VOLUMEUP"
0x02bd44 = "KEY_EPG"
0x02bd45 = "KEY_POWER2"